# Part 1

In [17]:
import pandas as pd
import numpy as np
df = pd.read_csv("capstone_data.csv")
df.head()

  Postal Code           Borough               Neighborhood
0         M1A      Not assigned                        NaN
1         M2A      Not assigned                        NaN
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

### Cleaning Data

In [18]:
df_1 = df.dropna(axis=0,subset = ["Neighborhood"])

In [19]:
df_1.head()

  Postal Code           Borough                                 Neighborhood
2         M3A        North York                                    Parkwoods
3         M4A        North York                             Victoria Village
4         M5A  Downtown Toronto                    Regent Park, Harbourfront
5         M6A        North York             Lawrence Manor, Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [20]:
df_1.shape

(103, 3)

# Part 2

In [21]:
df_2 = pd.read_csv("Geospatial_Coordinates.csv")
df_2.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [22]:
df_merge = df.merge(df_2)
df_merge.head()

,Postal Code,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494

In [25]:
df_merge["Borough"].unique()

array(['North York', 'Downtown Toronto', 'Etobicoke', 'Scarborough',
       'East York', 'York', 'East Toronto', 'West Toronto',
       'Central Toronto', 'Mississauga'], dtype=object)

In [29]:
df_merge[df_merge["Borough"].isin(["Downtown Toronto","East Toronto","West Toronto","Central Toronto"])][["Latitude","Longitude"]]

      Latitude  Longitude
2    43.654260 -79.360636
4    43.662301 -79.389494
9    43.657162 -79.378937
15   43.651494 -79.375418
19   43.676357 -79.293031
20   43.644771 -79.373306
24   43.657952 -79.387383
25   43.669542 -79.422564
30   43.650571 -79.384568
31   43.669005 -79.442259
36   43.640816 -79.381752
37   43.647927 -79.419750
41   43.679557 -79.352188
42   43.647177 -79.381576
43   43.636847 -79.428191
47   43.668999 -79.315572
48   43.648198 -79.379817
54   43.659526 -79.340923
61   43.728020 -79.388790
62   43.711695 -79.416936
67   43.712751 -79.390197
68   43.696948 -79.411307
69   43.661608 -79.464763
73   43.715383 -79.405678
74   43.672710 -79.405678
75   43.648960 -79.456325
79   43.704324 -79.388790
80   43.662696 -79.400049
81   43.651571 -79.484450
83   43.689574 -79.383160
84   43.653206 -79.400049
86   43.686412 -79.400049
87   43.628947 -79.394420
91   43.679563 -79.377529
92   43.646435 -79.374846
96   43.667967 -79.367675
97   43.648429 -79.382280
99   43.665860 -79.383160
100  43.662744 -79.321558

# Part 3

### Import necessary Libraries

In [1]:
import requests
import random


from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
    
# tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize


import folium # plotting library

print('Folium installed')
print('Libraries imported.')

Folium installed
Libraries imported.

### Define Foursquare Credentials and Version

In [2]:
CLIENT_ID = 'THEVKVPF0L35N5WB10O4ID3Z3WWTHUZF043N4CBFDDY5E1AB' # your Foursquare ID
CLIENT_SECRET = 'WBTR50DTBOVEQ5IN3DKNFU0KT1MGHJZ1IHXOGDKBTIDUMM5T' # your Foursquare Secret
VERSION = '20180604'
LIMIT = 30
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: THEVKVPF0L35N5WB10O4ID3Z3WWTHUZF043N4CBFDDY5E1AB
CLIENT_SECRET:WBTR50DTBOVEQ5IN3DKNFU0KT1MGHJZ1IHXOGDKBTIDUMM5T

In [3]:
address = 'Downtown Toronto'

geolocator = Nominatim(user_agent="foursquare_agent")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude

In [4]:
print(latitude, longitude)

43.6541737 -79.38081164513409

## 1. Search for a specific venue category

#### Now, let's assume that it is lunch time, and you are craving Italian food. So, let's define a query to search for Italian food that is within 500 metres from the Conrad Hotel.

In [8]:
search_query = 'Ita#### Now, let's assume that it is lunch time, and you are craving Italian food. So, let's define a query to search for Italian food that is within 500 metres from the Conrad Hotel. lian'
radius = 500
print(search_query + ' .... OK!')

Italian .... OK!

#### Define the corresponding URL

In [9]:
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=THEVKVPF0L35N5WB10O4ID3Z3WWTHUZF043N4CBFDDY5E1AB&client_secret=WBTR50DTBOVEQ5IN3DKNFU0KT1MGHJZ1IHXOGDKBTIDUMM5T&ll=43.6541737,-79.38081164513409&v=20180604&query=Italian&radius=500&limit=30'

#### Send the GET Request and examine the results

In [10]:
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5ec777203907e70028c49130'},
 'response': {'venues': [{'id': '4c787c9181bca0936180fa14',
    'name': 'Classic italian style pizza food truck',
    'location': {'address': 'CNE Midway',
     'lat': 43.652144,
     'lng': -79.381118,
     'labeledLatLngs': [{'label': 'display',
       'lat': 43.652144,
       'lng': -79.381118}],
     'distance': 227,
     'cc': 'CA',
     'city': 'Toronto',
     'state': 'ON',
     'country': 'Canada',
     'formattedAddress': ['CNE Midway', 'Toronto ON', 'Canada']},
    'categories': [{'id': '4bf58dd8d48988d1cb941735',
      'name': 'Food Truck',
      'pluralName': 'Food Trucks',
      'shortName': 'Food Truck',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/streetfood_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1590130560',
    'hasPerk': False},
   {'id': '573df789498e03dd8e54b166',
    'name': 'Mustachio Italian Eatery',
    'location': {'address': '595 Bay St',
     'crossStreet': 'Dundas St',
     'lat': 43.65616,
     'lng': -79.38319,
     'labeledLatLngs': [{'label': 'display',
       'lat': 43.65616,
       'lng': -79.38319}],
     'distance': 292,
     'postalCode': 'M5G 2C2',
     'cc': 'CA',
     'city': 'Toronto',
     'state': 'ON',
     'country': 'Canada',
     'formattedAddress': ['595 Bay St (Dundas St)',
      'Toronto ON M5G 2C2',
      'Canada']},
    'categories': [{'id': '4bf58dd8d48988d110941735',
      'name': 'Italian Restaurant',
      'pluralName': 'Italian Restaurants',
      'shortName': 'Italian',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/italian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1590130560',
    'hasPerk': False},
   {'id': '5e594c8a3de308000870c948',
    'name': 'Elm Street Italian Deli',
    'location': {'address': '15 Elm Street',
     'lat': 43.65769,
     'lng': -79.38248,
     'labeledLatLngs': [{'label': 'display',
       'lat': 43.65769,
       'lng': -79.38248}],
     'distance': 413,
     'postalCode': 'M5G 1G7',
     'cc': 'CA',
     'city': 'Toronto',
     'state': 'ON',
     'country': 'Canada',
     'formattedAddress': ['15 Elm Street', 'Toronto ON M5G 1G7', 'Canada']},
    'categories': [{'id': '4bf58dd8d48988d110941735',
      'name': 'Italian Restaurant',
      'pluralName': 'Italian Restaurants',
      'shortName': 'Italian',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/italian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1590130560',
    'hasPerk': False},
   {'id': '4f88cf84e4b002b90ab3b9b9',
    'name': "LA's Italian + Bar",
    'location': {'lat': 43.65053979517576,
     'lng': -79.38460322737672,
     'labeledLatLngs': [{'label': 'display',
       'lat': 43.65053979517576,
       'lng': -79.38460322737672}],
     'distance': 506,
     'cc': 'CA',
     'country': 'Canada',
     'formattedAddress': ['Canada']},
    'categories': [{'id': '4bf58dd8d48988d110941735',
      'name': 'Italian Restaurant',
      'pluralName': 'Italian Restaurants',
      'shortName': 'Italian',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/italian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1590130560',
    'hasPerk': False},
   {'id': '51bf3866498e55ee55df8db0',
    'name': 'The Fresh Italian',
    'location': {'lat': 43.654991437465284,
     'lng': -79.38789662900189,
     'labeledLatLngs': [{'label': 'display',
       'lat': 43.654991437465284,
       'lng': -79.38789662900189}],
     'distance': 577,
     'cc': 'CA',
     'city': 'Toronto',
     'state': 'ON',
     'country': 'Canada',
     'formattedAddress': ['Toronto ON', 'Canada']},
    'categories': [{'id': '4bf58dd8d48988d110941735',
      'name': 'Italian Restaurant',
      'pluralName': 'Italian Restaurants',
      'shortName': 'Italian',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/italian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1590130560',
    'hasPerk': False},
   {'id': '4b4a2d09f964a520687d26e3',
    'name': 'Sbarro',
    'location': {'address': '220 Yonge Street',
     'crossStreet': 'in Toronto Eaton Centre',
     'lat': 43.655413,
     'lng': -79.380896,
     'labeledLatLngs': [{'label': 'display',
       'lat': 43.655413,
       'lng': -79.380896}],
     'distance': 138,
     'postalCode': 'M5B 2H1',
     'cc': 'CA',
     'city': 'Toronto',
     'state': 'ON',
     'country': 'Canada',
     'formattedAddress': ['220 Yonge Street (in Toronto Eaton Centre)',
      'Toronto ON M5B 2H1',
      'Canada']},
    'categories': [{'id': '4bf58dd8d48988d1ca941735',
      'name': 'Pizza Place',
      'pluralName': 'Pizza Places',
      'shortName': 'Pizza',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/pizza_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1590130560',
    'hasPerk': False},
   {'id': '4b846dd4f964a520dc3431e3',
    'name': "Little Anthony's",
    'location': {'address': '121 Richmond St. W',
     'crossStreet': 'at York St.',
     'lat': 43.65029624519052,
     'lng': -79.38451301997945,
     'labeledLatLngs': [{'label': 'display',
       'lat': 43.65029624519052,
       'lng': -79.38451301997945}],
     'distance': 524,
     'postalCode': 'M5H 2K1',
     'cc': 'CA',
     'city': 'Toronto',
     'state': 'ON',
     'country': 'Canada',
     'formattedAddress': ['121 Richmond St. W (at York St.)',
      'Toronto ON M5H 2K1',
      'Canada']},
    'categories': [{'id': '4bf58dd8d48988d110941735',
      'name': 'Italian Restaurant',
      'pluralName': 'Italian Restaurants',
      'shortName': 'Italian',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/italian_',
       'suffix': '.png'},
      'primary': True}],
    'venuePage': {'id': '75877692'},
    'referralId': 'v-1590130560',
    'hasPerk': False},
   {'id': '516c1ef3e4b0b595c55461aa',
    'name': 'Consolato Italiano',
    'location': {'address': 'Beverly',
     'crossStreet': 'Dundas',
     'lat': 43.6540714381019,
     'lng': -79.37584957705431,
     'labeledLatLngs': [{'label': 'display',
       'lat': 43.6540714381019,
       'lng': -79.37584957705431}],
     'distance': 399,
     'cc': 'CA',
     'city': 'Toronto',
     'state': 'ON',
     'country': 'Canada',
     'formattedAddress': ['Beverly (Dundas)', 'Toronto ON', 'Canada']},
    'categories': [{'id': '4bf58dd8d48988d126941735',
      'name': 'Government Building',
      'pluralName': 'Government Buildings',
      'shortName': 'Government',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/building/government_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1590130560',
    'hasPerk': False}]}}

#### Get relevant part of JSON and transform it into a *pandas* dataframe

In [11]:
# assign relevant part of JSON to venues
venues = results['response']['venues']

# tranform venues into a dataframe
dataframe = json_normalize(venues)
dataframe.head()

,id,name,categories,referralId,hasPerk,location.address,location.lat,location.lng,location.labeledLatLngs,location.distance,location.cc,location.city,location.state,location.country,location.formattedAddress,location.crossStreet,location.postalCode,venuePage.id
0,4c787c9181bca0936180fa14,Classic italian style pizza food truck,"[{'id': '4bf58dd8d48988d1cb941735', 'name': 'F...",v-1590130560,False,CNE Midway,43.652144,-79.381118,"[{'label': 'display', 'lat': 43.652144, 'lng':...",227,CA,Toronto,ON,Canada,"[CNE Midway, Toronto ON, Canada]",NaN,NaN,NaN
1,573df789498e03dd8e54b166,Mustachio Italian Eatery,"[{'id': '4bf58dd8d48988d110941735', 'name': 'I...",v-1590130560,False,595 Bay St,43.656160,-79.383190,"[{'label': 'display', 'lat': 43.65616, 'lng': ...",292,CA,Toronto,ON,Canada,"[595 Bay St (Dundas St), Toronto ON M5G 2C2, C...",Dundas St,M5G 2C2,NaN
2,5e594c8a3de308000870c948,Elm Street Italian Deli,"[{'id': '4bf58dd8d48988d110941735', 'name': 'I...",v-1590130560,False,15 Elm Street,43.657690,-79.382480,"[{'label': 'display', 'lat': 43.65769, 'lng': ...",413,CA,Toronto,ON,Canada,"[15 Elm Street, Toronto ON M5G 1G7, Canada]",NaN,M5G 1G7,NaN
3,4f88cf84e4b002b90ab3b9b9,LA's Italian + Bar,"[{'id': '4bf58dd8d48988d110941735', 'name': 'I...",v-1590130560,False,NaN,43.650540,-79.384603,"[{'label': 'display', 'lat': 43.65053979517576...",506,CA,NaN,NaN,Canada,[Canada],NaN,NaN,NaN
4,51bf3866498e55ee55df8db0,The Fresh Italian,"[{'id': '4bf58dd8d48988d110941735', 'name': 'I...",v-1590130560,False,NaN,43.654991,-79.387897,"[{'label': 'display', 'lat': 43.65499143746528...",577,CA,Toronto,ON,Canada,"[Toronto ON, Canada]",NaN,NaN,NaN

#### Define information of interest and filter dataframe

In [12]:
# keep only columns that include venue name, and anything that is associated with location
filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe.loc[:, filtered_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row
dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term
dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]

dataframe_filtered

,name,categories,address,lat,lng,labeledLatLngs,distance,cc,city,state,country,formattedAddress,crossStreet,postalCode,id
0,Classic italian style pizza food truck,Food Truck,CNE Midway,43.652144,-79.381118,"[{'label': 'display', 'lat': 43.652144, 'lng':...",227,CA,Toronto,ON,Canada,"[CNE Midway, Toronto ON, Canada]",NaN,NaN,4c787c9181bca0936180fa14
1,Mustachio Italian Eatery,Italian Restaurant,595 Bay St,43.656160,-79.383190,"[{'label': 'display', 'lat': 43.65616, 'lng': ...",292,CA,Toronto,ON,Canada,"[595 Bay St (Dundas St), Toronto ON M5G 2C2, C...",Dundas St,M5G 2C2,573df789498e03dd8e54b166
2,Elm Street Italian Deli,Italian Restaurant,15 Elm Street,43.657690,-79.382480,"[{'label': 'display', 'lat': 43.65769, 'lng': ...",413,CA,Toronto,ON,Canada,"[15 Elm Street, Toronto ON M5G 1G7, Canada]",NaN,M5G 1G7,5e594c8a3de308000870c948
3,LA's Italian + Bar,Italian Restaurant,NaN,43.650540,-79.384603,"[{'label': 'display', 'lat': 43.65053979517576...",506,CA,NaN,NaN,Canada,[Canada],NaN,NaN,4f88cf84e4b002b90ab3b9b9
4,The Fresh Italian,Italian Restaurant,NaN,43.654991,-79.387897,"[{'label': 'display', 'lat': 43.65499143746528...",577,CA,Toronto,ON,Canada,"[Toronto ON, Canada]",NaN,NaN,51bf3866498e55ee55df8db0
5,Sbarro,Pizza Place,220 Yonge Street,43.655413,-79.380896,"[{'label': 'display', 'lat': 43.655413, 'lng':...",138,CA,Toronto,ON,Canada,"[220 Yonge Street (in Toronto Eaton Centre), T...",in Toronto Eaton Centre,M5B 2H1,4b4a2d09f964a520687d26e3
6,Little Anthony's,Italian Restaurant,121 Richmond St. W,43.650296,-79.384513,"[{'label': 'display', 'lat': 43.65029624519052...",524,CA,Toronto,ON,Canada,"[121 Richmond St. W (at York St.), Toronto ON ...",at York St.,M5H 2K1,4b846dd4f964a520dc3431e3
7,Consolato Italiano,Government Building,Beverly,43.654071,-79.375850,"[{'label': 'display', 'lat': 43.6540714381019,...",399,CA,Toronto,ON,Canada,"[Beverly (Dundas), Toronto ON, Canada]",Dundas,NaN,516c1ef3e4b0b595c55461aa

#### Let's visualize the Italian restaurants that are nearby

In [13]:
dataframe_filtered.name

0    Classic italian style pizza food truck
1                  Mustachio Italian Eatery
2                   Elm Street Italian Deli
3                        LA's Italian + Bar
4                         The Fresh Italian
5                                    Sbarro
6                          Little Anthony's
7                        Consolato Italiano
Name: name, dtype: object

In [14]:
venues_map = folium.Map(location=[latitude, longitude], zoom_start=13) # generate map centred around the Conrad Hotel

# add a red circle marker to represent the Conrad Hotel
folium.features.CircleMarker(
    [latitude, longitude],
    radius=10,
    color='red',
    popup='Conrad Hotel',
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(venues_map)

# add the Italian restaurants as blue circle markers
for lat, lng, label in zip(dataframe_filtered.lat, dataframe_filtered.lng, dataframe_filtered.categories):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        popup=label,
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(venues_map)

# display map
venues_map